### ISSUE TITLE
Filters on video

### ISSUE THREAD

**Issue by kisso** [MyCometG3/DLABridging#12]
Hi, is it possible to apply image filters? for example grayscale, image rotation etc... Have you already tried it? I need to apply filter which will be in video preview and also in recorded video. What do you think about performance? Or should I use metal for this feature?

**Comment by MyCometG3** [comment]
No. It is out-of-scope from this framework.
I think you need to do extra work on your side.

- All filter operation should be performed inside GPU world. Use CoreImage, etc.
- Render CVPixelBuffer into CIImage
- Apply CIFilter into CIImage
- Create output CVPixelBuffer with applied CIImage
- Create new CMSampleBuffer using CVPixelBuffer with proper orientation info
- Enqueue CMSampleBuffer into export session and/or display session
- For Image quality, either YUV444 or RGB444 format run better than yuv422/yuv420 format.

Also you need to separate pipeline for export and display.
- Use most of GPU performace to process real time processing for export
- To save GPU memory, reduce display image resolution into half or quarter size
- Display pipeline must support instant frame drop - you need to track display time stamp of CMSampleBuffer continuously

**Comment by kisso** [comment]
thank you for hint
