### ISSUE TITLE
XPC event error 'connection invalid' in DLABBrowser

### ISSUE THREAD

**Issue by kisso** [MyCometG3/DLABridging#13]
Hi, I want to use dlabbrowser for detecting device, but it is not working I use code:

```
import AppKit
import DLABridging

class ViewController: NSViewController {
    var browser: DLABBrowser = DLABBrowser()

    override func viewDidLoad() {
        super.viewDidLoad()

        browser.delegate = self
        browser.startForInput()
    }
}

extension ViewController: DLABBrowserDelegate {
    func didAdd(_ device: DLABDevice, of sender: DLABBrowser) {
        print("added")
    }

    func didRemove(_ device: DLABDevice, of sender: DLABBrowser) {
        print("removed")
    }
}
```

I am getting this error:
*** sendMessageWithReply_block_invoke[225]: XPC event error 'connection invalid'
*** waitForReply[400]: Error completing transaction (connection invalid)
*** completeTransactionAndProcessReply[385]: Error waiting for transaction reply
*** CreateNewClient[26]: Couldnt connect to XPC service

**Comment by kisso** [comment]
I found the problem, you need to disable app sandboxing

**Comment by MyCometG3** [comment]
Works as intended.
