### ISSUE TITLE
Notifications for Connected/Disconnected Devices

### ISSUE THREAD

**Issue by sqwk** [MyCometG3/DLABridging#16]
Is there a way to notify an app when DeckLink devices have been connected/disconnected? Using `IOKit` to handle new plugged in devices, followed by a call to `DLABBrowser.registerDevices()` and checking `DLABBrowser.allDevices` seems to work, but is there a built in event? (I am using the DLAB Swift package.) Calling `DLABBrowser.start()`seems to start the detection of devices, but I am not sure how to subscribe to any connection/disconnection events.

**Comment by MyCometG3** [comment]
DLABBrowserDelegate protocol could work.

	import Cocoa
	import DLABridging
	import DLABCaptureManager
	
	@NSApplicationMain
	class AppDelegate: NSObject, NSApplicationDelegate, DLABBrowserDelegate {
	    func applicationDidFinishLaunching(_ aNotification: Notification) {
	        dumpDeviceList()
	    }
	    func applicationWillTerminate(_ aNotification: Notification) {
	        browser = nil
	        manager = nil
	    }
	    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool {
	        return true
	    }
	    
	    var manager :CaptureManager? = nil
	    var browser :DLABBrowser? = nil
	    func dumpDeviceList() {
	        if manager == nil {
	            manager = CaptureManager()
	        }
	        if browser == nil {
	            browser = DLABBrowser()
	        }
	        
	        if let browser = browser {
	            browser.delegate = self
	            print("start!")
	            browser.start()
	            // print(">>running: \(browser.isRunning)")
	            
	            DispatchQueue.main.asyncAfter(deadline: .now() + 30, execute: { () in
	                print("stop!")
	                browser.stop()
	                // print(">>running: \(browser.isRunning)")
	            })
	        }
	    }
	    func didAdd(_ device: DLABDevice, of sender: DLABBrowser) {
	        print ("didAdd")
	        
	        // Handle hot add w/ manager...
	    }
	    func didRemove(_ device: DLABDevice, of sender: DLABBrowser) {
	        print ("didRemove")
	        
	        // Handle hot remove w/ manager...
	    }
	}

**Comment by sqwk** [comment]
Many thanks for the heads up. Works as expected. One can also separate `NSApplicationDelegate` and `DLABBrowserDelegate` and create a separate class. Also works.
