### ISSUE TITLE
Problem detecting device

### ISSUE THREAD

**Issue by igomez084** [MyCometG3/DLABridging#2]
Hello, I am trying to include the ability of recording using the blackmagic recorder in my project. Until now, I could not find anything useful (written in swift) so I was happy to to find out your work.

However, I have not been successful implementing your framework, as I cannot detect my device (H.264 pro recorder). I tried like is suggested, but my deviceList is an empty array:

```
  let browser = DLABBrowser()
  _ = browser.registerDevicesForOutput()
  let deviceList = browser.allDevices
  device = deviceList.first!
```

I have tested the recorder with the blackmagic software and it is detected and working perfectly. What could be the problem?

Thank you in advance.

**Comment by MyCometG3** [comment]
Unfortunately it is not supported. This framework only works with uncompressed capture device for now.

H.264 Pro Recorder is categorized as "Streaming Encoder" and different API interface is required to support. Please take a look at Blackmagic DeckLink SDK Section 2.4.5 for Capture implementation.

**Comment by MyCometG3** [comment]
One thing, I am not sure but if H.264 pro recorder is device for OUTPUT, use 
browser.registerDevicesForOutput()
and If it is for INPUT, try
browser.registerDevicesForInput()

If the device supports both "compressed" and "decompressed" stream, this framework only work with "decompressed" capture.

**Comment by igomez084** [comment]
Thank you very much for the quick response. Unfortunately, it is not working with browser.registerDevicesForInput() neither with browser.registerDevicesForOutput()

I may have access to a different recorder, blackmagic mini ultra studio. Will be different with this recorder? Sorry but I am not really familiar with those devices.

Thank you very much once again.

**Comment by MyCometG3** [comment]
I hope this would help.
//
Blackmagic DeckLink SDK May 2019 (SDK 11.2)
P.19 Section 2 - DeckLink API 2.2 Sandboxing support on macOS
>com.apple.security.temporary-exception.mach-lookup.global-name
>com.blackmagic-design.desktopvideo.DeckLinkHardwareXPCService
