### ISSUE TITLE
Simultaneous play record

### ISSUE THREAD

**Issue by igomez084** [MyCometG3/DLABridging#3]
Hello,

I would like to ask if it is possible to play the video while recording it. I would like to capture an event and while doing so, go back to one specific momento to review it.

Thank you in advance!

**Comment by MyCometG3** [comment]
You have to do much by your own code. 

DLABridging.framework does not provide any time shift feature. It simply passes CMSampleBuffer one each via callback to user application only. Audio and Video callback could be triggered in different time resolution. 
If you want to do time shift while capture is running, you have to 1) deep copy sample buffer every time, and create two stream which 2)produces buffer stream for “time shift cache - delayed playback”, and 3)write sample buffer into captured movie file.

Yes it will be possible though, quite hard to handle delayed play on demand.
