### ISSUE TITLE
4k input?

### ISSUE THREAD

**Issue by kcwvc52** [MyCometG3/DLABridging#4]
is this able to receive 4k input from decklink 4k cards?

**Comment by MyCometG3** [comment]
I am not sure but I guess so.

DeckLink SDI 4K also uses Blackmagic_Desktop_Video_12.1 / Blackmagic_DeckLink_SDK_12.1, which is exactly same SW I use w/ Intensity Shuttle Thunderbolt Today.

NOTE: I have no MacPro nor DeckLink SDI 4K cards though, this Framework itself does not block 4k input via 6G-SDI.

**Comment by kcwvc52** [comment]
awesome!
