### ISSUE TITLE
/System/Library/Frameworks/DLABridging.framework/Versions/A/DLABridging (no such file)

### ISSUE THREAD

**Issue by kisso** [MyCometG3/DLABridging#5]
Hi, I build framework in xcode then exported in another project, where I am getting error /System/Library/Frameworks/DLABridging.framework/Versions/A/DLABridging (no such file). Can you please tell me what am I doing wrong?

Thank you
Have a nice day

**Comment by kisso** [comment]
I fixed it, now getting: dyld[20043]: Library not loaded: /Library/Frameworks/DeckLinkAPI.framework/Versions/A/DeckLinkAPI
  Referenced from: /Users/kisso/Library/Developer/Xcode/DerivedData/Photoshop-blyaomvesorxkudytitzixywnugo/Build/Products/Debug/Photoshop.app/Contents/Frameworks/DLABridging.framework/Versions/A/DLABridging
  Reason: tried: '/Users/kisso/Library/Developer/Xcode/DerivedData/Photoshop-blyaomvesorxkudytitzixywnugo/Build/Products/Debug/DeckLinkAPI.framework/Versions/A/DeckLinkAPI' (no such file), '/Library/Frameworks/DeckLinkAPI.framework/Versions/A/DeckLinkAPI' (code signature in <F1D8F5A3-0959-36E4-9579-E8B57A48920F> '/Library/Frameworks/DeckLinkAPI.framework/Versions/A/DeckLinkAPI' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Library/Frameworks/DeckLinkAPI.framework/Versions/A/DeckLinkAPI' (no such file)

**Comment by MyCometG3** [comment]
1) Confirm dependency.
Confirm /Library/Frameworks/DeckLinkAPI.framework is there. if not, you need to install first.

2) Framework search path misconfiguration
/System/Library/Frameworks is reserved by Apple. You cannot use there. 
Instead, try to export into /Library/Frameworks for all user in the Mac, or /User/xxxx/Library/Frameworks for specific user.
If you can, embed framework into your application bundle. (my app recDL is built in such way.)

3) Code signature issue
Verify the Framework is properly code-signed by your dev-ID same as the application which is signed by your dev-ID.

4) Sandbox restriction:
See following in DeckLink SDK pdf.
Section 2 - DeckLink API >> 2.2 Sandboxing support on macOS

**Comment by kisso** [comment]
Now it's working, thank you so much and also thank you for this awesome wrapper.
