### ISSUE TITLE
Multiple streams at the same time

### ISSUE THREAD

**Issue by kisso** [MyCometG3/DLABridging#6]
Does your wrapper support synchronized streams from multiple video inputs at the same time?

**Comment by MyCometG3** [comment]
Unfortunately this framework itself does not support multiple input - single input for single instance.

I am not sure if it properly works with multiple instances (synced) but as far as I know most of API (excl' compressed capture) are implemented into Obj-C.

**Comment by kisso** [comment]
may I get contact on you? skype or discord or any other platform?

**Comment by MyCometG3** [comment]
Sorry I cannot help on multiple input question - I do not have any device to verify the actual behavior.
