### ISSUE TITLE
Establish available and active connections

### ISSUE THREAD

**Issue by dsmurfin** [MyCometG3/DLABridging#7]
It would be great to provide methods for establishing the available video/audio connections, and active video/audio connection for each device:

```
BMDDeckLinkVideoOutputConnections  = /* 'vocn' */ 0x766F636E,	// Returns a BMDVideoConnection bit field
BMDDeckLinkVideoInputConnections   = /* 'vicn' */ 0x7669636E,	// Returns a BMDVideoConnection bit field
BMDDeckLinkAudioOutputConnections  = /* 'aocn' */ 0x616F636E,	// Returns a BMDAudioConnection bit field
BMDDeckLinkAudioInputConnections   = /* 'aicn' */ 0x6169636E,	// Returns a BMDAudioConnection bit field
```

**Comment by MyCometG3** [comment]
Per native Decklink API design, each connections are managed by profile.
- See IDeckLinkProfileAttributes (SDK pdf section 2.5.17) about BMDDeckLinkAttributeID.
- BMDDeckLinkAttributeID (SDK pdf section 3.17) using IDeckLinkProfileAttributes for available connections: 
	BMDDeckLinkVideoOutputConnections
	BMDDeckLinkAudioOutputConnections
	BMDDeckLinkVideoOutputConnections
	BMDDeckLinkAudioOutputConnections
- All BMDDeckLinkAttributeID are translated into DLABAttributeXXX. See DLABConstants.h.
/*=====*/
Using native APIs w/ Objective-C++, it will be like:
    BMDDeckLinkAttributeID attr = attributeID;
    int64_t newIntValue = 0;
    result = _deckLinkProfileAttributes->GetInt(attr, &newIntValue);
    return @(newIntValue);
/*=====*/
Under DLABridging, DLABDevice provides query interface for Attribute IDs.
    open func intValue(for attributeID: DLABAttribute) throws -> NSNumber
Running profileID is also available:
    open var profileID: Int64 { get }
/*=====*/
To query/change DeckLinkProfileAttributes, you can use following methods
    open func availableProfileAttributes() throws -> [DLABProfileAttributes]
    open func activateProfile(_ targetProfileID: NSNumber) throws
    open func checkRunningProfile(_ targetProfileID: NSNumber) throws -> NSNumber
    open func activateProfile(using attributes: DLABProfileAttributes) throws
    open func checkRunningProfile(using attributes: DLABProfileAttributes) throws -> NSNumber
/*=====*/

**Comment by dsmurfin** [comment]
This is perfect, thank you so much. I had totally missed this part of the API.

Thanks for all your work on this library, it's really excellent.

**Comment by dsmurfin** [comment]
I've just had a look at this now.

I am encountering the following issue:

`Error Domain=com.MyCometG3.DLABridging.ErrorDomain Code=-2147483644 "-[DLABDevice(Profile) availableProfileAttributesWithError:] (100)" UserInfo={NSLocalizedDescription=-[DLABDevice(Profile) availableProfileAttributesWithError:] (100), NSLocalizedFailureReason=IDeckLinkProfileManager is not supported.}`

``` swift
do {
    let attributes = try device.availableProfileAttributes()
    print(attributes)
} catch {
    print(error)
}
```

My understanding according to the docs is that a device with a single profile returns an error:

`NOTE If a DeckLink device only has a single profile, then QueryInterface will fail and return
 E_NOINTERFACE` (2.5.46)

I am using an UltraStudio 3G which has both SDI and HDMI selection.

**Comment by MyCometG3** [comment]
Thank you for your update. I again reviewed the SDK docs.

Per SDK Doc 2.4.11 Device Profiles, 

>Certain DeckLink devices such as the DeckLink 8K Pro, the DeckLink Quad 2 and the DeckLink Duo 2 support multiple profiles to configure the capture and playback behavior of its sub-devices.


It seems basic idea of multiple profile is to define combination-of-multiple-input/output-ports, so simple devices such like UltraStudio 3G would have no IDeckLinkProfileManager support.

Even single profile device should work with IDeckLinkProfileAttributes. Please try 
	open func intValue(for attributeID: DLABAttribute) throws -> NSNumber
for available port query.

**Comment by dsmurfin** [comment]
> Even single profile device should work with IDeckLinkProfileAttributes. Please try
> open func intValue(for attributeID: DLABAttribute) throws -> NSNumber
> for available port query.

That does it, thanks!
