### ISSUE TITLE
having to force unwrap device from device browser 

### ISSUE THREAD

**Issue by fuccimain** [MyCometG3/DLABridging#8]
let browser = DLABBrowser()
        _ = browser.registerDevicesForInput()
        let deviceList = browser.allDevices
          print(deviceList)
          bmDevice2 = deviceList?.first
          print(bmDevice2?.displayName)
         // let device3 = device2.modelName
           bmDevice3 = browser.device(withModelName: "UltraStudio Recorder 3G", displayName: "UltraStudio Recorder 3G")
////////////////////////

do {
            try bmDevice3?.setInputScreenPreviewTo(videoView)

/////////////////////

otherwise I get compile errors: 
Value of optional type 'DLABDevice?' must be unwrapped to refer to member 'displayName' of wrapped base type 'DLABDevice'

and

Expression implicitly coerced from '[DLABDevice]?' to 'Any'

**Comment by MyCometG3** [comment]
DLABBrowser.h (Swift 5 Interface) would be:

    open var allDevices: [DLABDevice]? { get }
    open func device(withModelName model: String, displayName display: String) -> DLABDevice?

As all are optional type, you need to unwrap first.

        do {
            let browser = DLABBrowser()
            _ = browser.registerDevicesForInput()
            
            guard let allDevices = browser.allDevices else { return }
            guard let device = allDevices.first else { return }
            
            let modelName = device.modelName, displayName = device.displayName
            if let tempDevice = browser.device(withModelName: modelName, displayName: displayName) {
                print("found!")
            } else {
                print("not found!")
            }
            
            var info :[String:Any] = [:]
            do {
                info["modelName"] = device.modelName // NSString* -> String
                info["displayName"] = device.displayName // NSString* -> String
                info["persistentID"] = device.persistentID // int64_t -> Int64
                info["deviceGroupID"] = device.deviceGroupID // int64_t -> Int64
                info["topologicalID"] = device.topologicalID // int64_t -> Int64
                info["numberOfSubDevices"] = device.numberOfSubDevices // int64_t -> Int64
                info["subDeviceIndex"] = device.subDeviceIndex // int64_t -> Int64
                info["profileID"] = device.profileID // int64_t -> Int64
                info["duplex"] = device.duplex // int64_t -> Int64
                info["supportFlag"] = device.supportFlag // uint32_t -> UInt32
                info["supportCapture"] = device.supportCapture // BOOL
                info["supportPlayback"] = device.supportPlayback // BOOL
                info["supportKeying"] = device.supportKeying // BOOL
                info["supportInputFormatDetection"] = device.supportInputFormatDetection // BOOL
                info["supportHDRMetadata"] = device.supportHDRMetadata // BOOL
            }
            print( info )
        }
